// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

type Encoding = int8
const (
	EncodingPLAIN Encoding = 0
	/// Data is stored dictionary-encoded
	/// dictionary size: <INT32 Dictionary size>
	/// dictionary data: <TYPE primitive array>
	/// dictionary index: <INT32 primitive array>
	///
	/// TODO: do we care about storing the index values in a smaller typeclass
	EncodingDICTIONARY Encoding = 1
)

var EnumNamesEncoding = map[Encoding]string{
	EncodingPLAIN:"PLAIN",
	EncodingDICTIONARY:"DICTIONARY",
}

