// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

type TimeUnit = int8
const (
	TimeUnitSECOND TimeUnit = 0
	TimeUnitMILLISECOND TimeUnit = 1
	TimeUnitMICROSECOND TimeUnit = 2
	TimeUnitNANOSECOND TimeUnit = 3
)

var EnumNamesTimeUnit = map[TimeUnit]string{
	TimeUnitSECOND:"SECOND",
	TimeUnitMILLISECOND:"MILLISECOND",
	TimeUnitMICROSECOND:"MICROSECOND",
	TimeUnitNANOSECOND:"NANOSECOND",
}

