// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

/// Feather is an experimental serialization format implemented using
/// techniques from Apache Arrow. It was created as a proof-of-concept of an
/// interoperable file format for storing data frames originating in Python or
/// R. It enabled the developers to sidestep some of the open design questions
/// in Arrow from early 2016 and instead create something simple and useful for
/// the intended use cases.
type TypE = int8
const (
	TypEBOOL TypE = 0
	TypEINT8 TypE = 1
	TypEINT16 TypE = 2
	TypEINT32 TypE = 3
	TypEINT64 TypE = 4
	TypEUINT8 TypE = 5
	TypEUINT16 TypE = 6
	TypEUINT32 TypE = 7
	TypEUINT64 TypE = 8
	TypEFLOAT TypE = 9
	TypEDOUBLE TypE = 10
	TypEUTF8 TypE = 11
	TypEBINARY TypE = 12
	TypECATEGORY TypE = 13
	TypETIMESTAMP TypE = 14
	TypEDATE TypE = 15
	TypETIME TypE = 16
)

var EnumNamesTypE = map[TypE]string{
	TypEBOOL:"BOOL",
	TypEINT8:"INT8",
	TypEINT16:"INT16",
	TypEINT32:"INT32",
	TypEINT64:"INT64",
	TypEUINT8:"UINT8",
	TypEUINT16:"UINT16",
	TypEUINT32:"UINT32",
	TypEUINT64:"UINT64",
	TypEFLOAT:"FLOAT",
	TypEDOUBLE:"DOUBLE",
	TypEUTF8:"UTF8",
	TypEBINARY:"BINARY",
	TypECATEGORY:"CATEGORY",
	TypETIMESTAMP:"TIMESTAMP",
	TypEDATE:"DATE",
	TypETIME:"TIME",
}

