// automatically generated by the FlatBuffers compiler, do not modify

package fbs

const (
	TypeMetadataNONE = 0
	TypeMetadataCategoryMetadata = 1
	TypeMetadataTimestampMetadata = 2
	TypeMetadataDateMetadata = 3
	TypeMetadataTimeMetadata = 4
)

var EnumNamesTypeMetadata = map[int]string{
	TypeMetadataNONE:"NONE",
	TypeMetadataCategoryMetadata:"CategoryMetadata",
	TypeMetadataTimestampMetadata:"TimestampMetadata",
	TypeMetadataDateMetadata:"DateMetadata",
	TypeMetadataTimeMetadata:"TimeMetadata",
}

