// automatically generated by the FlatBuffers compiler, do not modify

package fbs

/// Feather is an experimental serialization format implemented using
/// techniques from Apache Arrow. It was created as a proof-of-concept of an
/// interoperable file format for storing data frames originating in Python or
/// R. It enabled the developers to sidestep some of the open design questions
/// in Arrow from early 2016 and instead create something simple and useful for
/// the intended use cases.
const (
	TypEBOOL      = 0
	TypEINT8      = 1
	TypEINT16     = 2
	TypEINT32     = 3
	TypEINT64     = 4
	TypEUINT8     = 5
	TypEUINT16    = 6
	TypEUINT32    = 7
	TypEUINT64    = 8
	TypEFLOAT     = 9
	TypEDOUBLE    = 10
	TypEUTF8      = 11
	TypEBINARY    = 12
	TypECATEGORY  = 13
	TypETIMESTAMP = 14
	TypEDATE      = 15
	TypETIME      = 16
)

var EnumNamesTypE = map[int]string{
	TypEBOOL:      "BOOL",
	TypEINT8:      "INT8",
	TypEINT16:     "INT16",
	TypEINT32:     "INT32",
	TypEINT64:     "INT64",
	TypEUINT8:     "UINT8",
	TypEUINT16:    "UINT16",
	TypEUINT32:    "UINT32",
	TypEUINT64:    "UINT64",
	TypEFLOAT:     "FLOAT",
	TypEDOUBLE:    "DOUBLE",
	TypEUTF8:      "UTF8",
	TypEBINARY:    "BINARY",
	TypECATEGORY:  "CATEGORY",
	TypETIMESTAMP: "TIMESTAMP",
	TypEDATE:      "DATE",
	TypETIME:      "TIME",
}
