// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

type TypeMetadata = byte
const (
	TypeMetadataNONE TypeMetadata = 0
	TypeMetadataCategoryMetadata TypeMetadata = 1
	TypeMetadataTimestampMetadata TypeMetadata = 2
	TypeMetadataDateMetadata TypeMetadata = 3
	TypeMetadataTimeMetadata TypeMetadata = 4
)

var EnumNamesTypeMetadata = map[TypeMetadata]string{
	TypeMetadataNONE:"NONE",
	TypeMetadataCategoryMetadata:"CategoryMetadata",
	TypeMetadataTimestampMetadata:"TimestampMetadata",
	TypeMetadataDateMetadata:"DateMetadata",
	TypeMetadataTimeMetadata:"TimeMetadata",
}

